"""add surname to author

Revision ID: a6fda81ba534
Revises: bde43a419b6b
Create Date: 2024-01-24 11:49:36.904652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fda81ba534'
down_revision: Union[str, None] = 'bde43a419b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('surname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'surname')
    # ### end Alembic commands ###
