from __future__ import annotations

import json
import logging
from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator, Sequence
from dataclasses import dataclass

from app.config import Settings, get_settings

logger = logging.getLogger(__name__)


class ProviderError(RuntimeError):
    pass


@dataclass(slots=True)
class ProviderMessage:
    role: str
    content: str


class BaseModelProvider(ABC):
    def __init__(self, model_name: str, settings: Settings | None = None, slot: str = "unknown") -> None:
        self.model_name = model_name
        self.settings = settings or get_settings()
        # Orchestrator slot this instance serves (actor/memory/embedding/gm).
        # Attached to token metrics/spans so slots stay distinguishable even in
        # DEV_MODE, where the text slots all share one model name.
        self.slot = slot

    async def aclose(self) -> None:
        """Release the underlying HTTP client, if any. Idempotent.

        Handles both ``httpx.AsyncClient`` (``aclose``) and the OpenAI SDK
        client (``close``), so subclasses don't each need their own teardown.
        """
        client = getattr(self, "client", None)
        if client is None:
            return
        closer = getattr(client, "aclose", None) or getattr(client, "close", None)
        if closer is not None:
            await closer()

    @abstractmethod
    async def generate_text(
        self,
        messages: Sequence[ProviderMessage],
        *,
        temperature: float,
        max_tokens: int,
        json_mode: bool = False,
    ) -> str:
        raise NotImplementedError

    @abstractmethod
    async def generate_text_stream(
        self,
        messages: Sequence[ProviderMessage],
        *,
        temperature: float,
        max_tokens: int,
    ) -> AsyncGenerator[str, None]:
        """Yield text chunks as they are generated by the model."""
        raise NotImplementedError
        yield  # pragma: no cover - makes this an async generator

    @abstractmethod
    async def embed_texts(self, texts: Sequence[str]) -> list[list[float]]:
        raise NotImplementedError

    async def generate_json(
        self,
        messages: Sequence[ProviderMessage],
        *,
        temperature: float,
        max_tokens: int,
    ) -> dict:
        raw_text = await self.generate_text(
            messages,
            temperature=temperature,
            max_tokens=max_tokens,
            json_mode=True,
        )
        try:
            return json.loads(raw_text)
        except json.JSONDecodeError as exc:
            logger.exception("Invalid JSON from %s: %s", self.__class__.__name__, raw_text[:200])
            raise ProviderError(f"{self.__class__.__name__} returned invalid JSON: {raw_text}") from exc


def build_provider(
    provider_name: str, model_name: str, settings: Settings | None = None, slot: str = "unknown"
) -> BaseModelProvider:
    resolved_settings = settings or get_settings()
    if provider_name == "openai":
        from app.providers.openai_provider import OpenAIProvider

        return OpenAIProvider(model_name=model_name, settings=resolved_settings, slot=slot)

    if provider_name == "ollama":
        from app.providers.ollama_provider import OllamaProvider

        return OllamaProvider(model_name=model_name, settings=resolved_settings, slot=slot)

    if provider_name == "mock":
        from app.providers.mock_provider import MockProvider

        return MockProvider(model_name=model_name, settings=resolved_settings, slot=slot)

    raise ProviderError(f"Unsupported provider: {provider_name}")
