from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from typing import Any, cast

from openai import AsyncOpenAI
from openai.types.chat import ChatCompletionMessageParam

from app.providers.base import BaseModelProvider, ProviderError, ProviderMessage


class OpenAIProvider(BaseModelProvider):
    def __init__(self, model_name: str, settings: Any) -> None:
        super().__init__(model_name=model_name, settings=settings)
        if not self.settings.openai_api_key:
            raise ProviderError("OPENAI_API_KEY is required when an OpenAI provider is selected.")

        self.client = AsyncOpenAI(
            api_key=self.settings.openai_api_key,
            base_url=self.settings.openai_base_url if self.settings.openai_base_url else None,
        )

    def _to_openai_messages(self, messages: Sequence[ProviderMessage]) -> list[ChatCompletionMessageParam]:
        return cast(
            list[ChatCompletionMessageParam],
            [{"role": message.role, "content": message.content} for message in messages],
        )

    async def generate_text(
        self,
        messages: Sequence[ProviderMessage],
        *,
        temperature: float,
        max_tokens: int,
        json_mode: bool = False,
    ) -> str:
        kwargs: dict[str, Any] = {
            "model": self.model_name,
            "messages": self._to_openai_messages(messages),
            "temperature": temperature,
            "max_completion_tokens": max_tokens,
        }
        if json_mode:
            kwargs["response_format"] = {"type": "json_object"}

        response = await self.client.chat.completions.create(**kwargs)
        content = response.choices[0].message.content
        if not content:
            raise ProviderError("OpenAI provider returned an empty completion.")
        return content

    async def generate_text_stream(
        self,
        messages: Sequence[ProviderMessage],
        *,
        temperature: float,
        max_tokens: int,
    ) -> AsyncIterator[str]:
        """Stream text chunks as they are generated by OpenAI."""
        stream = await self.client.chat.completions.create(
            model=self.model_name,
            messages=self._to_openai_messages(messages),
            temperature=temperature,
            max_completion_tokens=max_tokens,
            stream=True,
        )
        async for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content:
                yield chunk.choices[0].delta.content

    async def embed_texts(self, texts: Sequence[str]) -> list[list[float]]:
        response = await self.client.embeddings.create(
            model=self.model_name,
            input=list(texts),
            dimensions=self.settings.embedding_dimension,
        )
        return [item.embedding for item in response.data]
