from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from time import perf_counter
from typing import Any, cast

from openai import AsyncOpenAI
from openai.types.chat import ChatCompletionMessageParam

from app.providers.base import BaseModelProvider, ProviderError, ProviderMessage
from app.telemetry import (
    llm_latency,
    llm_span,
    record_llm_tokens,
    record_span_error,
    set_completion,
    set_prompt,
    tracer,
)


class OpenAIProvider(BaseModelProvider):
    def __init__(self, model_name: str, settings: Any) -> None:
        super().__init__(model_name=model_name, settings=settings)
        if not self.settings.openai_api_key:
            raise ProviderError("OPENAI_API_KEY is required when an OpenAI provider is selected.")

        self.client = AsyncOpenAI(
            api_key=self.settings.openai_api_key,
            base_url=self.settings.openai_base_url if self.settings.openai_base_url else None,
        )

    def _to_openai_messages(self, messages: Sequence[ProviderMessage]) -> list[ChatCompletionMessageParam]:
        # cast is load-bearing, NOT redundant: our messages carry a plain str
        # `role`, which mypy can't match against the strict ChatCompletionMessageParam
        # TypedDict union (each requires a literal role). Removing it reintroduces
        # a [misc] type error. (See branch history: a bot "fix" wrongly dropped it.)
        return cast(
            list[ChatCompletionMessageParam],
            [{"role": message.role, "content": message.content} for message in messages],
        )

    async def generate_text(
        self,
        messages: Sequence[ProviderMessage],
        *,
        temperature: float,
        max_tokens: int,
        json_mode: bool = False,
    ) -> str:
        kwargs: dict[str, Any] = {
            "model": self.model_name,
            "messages": self._to_openai_messages(messages),
            "temperature": temperature,
            "max_completion_tokens": max_tokens,
        }
        if json_mode:
            kwargs["response_format"] = {"type": "json_object"}

        with llm_span(
            "llm.generate_text",
            "openai",
            self.model_name,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
        ) as span:
            response = await self.client.chat.completions.create(**kwargs)
            content = response.choices[0].message.content
            if not content:
                raise ProviderError("OpenAI provider returned an empty completion.")
            set_completion(span, content)
            usage = response.usage
            if usage:
                span.set_attribute("gen_ai.usage.input_tokens", usage.prompt_tokens)
                span.set_attribute("gen_ai.usage.output_tokens", usage.completion_tokens)
                record_llm_tokens("openai", self.model_name, usage.prompt_tokens, usage.completion_tokens)
            return content

    async def generate_text_stream(
        self,
        messages: Sequence[ProviderMessage],
        *,
        temperature: float,
        max_tokens: int,
    ) -> AsyncIterator[str]:
        """Stream text chunks as they are generated by OpenAI."""
        # Manual span (not current) because this generator yields between awaits.
        span = tracer.start_span("llm.generate_text_stream")
        span.set_attribute("gen_ai.system", "openai")
        span.set_attribute("gen_ai.request.model", self.model_name)
        span.set_attribute("gen_ai.request.temperature", temperature)
        span.set_attribute("gen_ai.request.max_tokens", max_tokens)
        set_prompt(span, messages)
        parts: list[str] = []
        usage = None
        start = perf_counter()
        try:
            stream = await self.client.chat.completions.create(
                model=self.model_name,
                messages=self._to_openai_messages(messages),
                temperature=temperature,
                max_completion_tokens=max_tokens,
                stream=True,
                stream_options={"include_usage": True},
            )
            async for chunk in stream:
                if chunk.usage:
                    usage = chunk.usage
                if chunk.choices and chunk.choices[0].delta.content:
                    parts.append(chunk.choices[0].delta.content)
                    yield chunk.choices[0].delta.content
            set_completion(span, "".join(parts))
            if usage:
                span.set_attribute("gen_ai.usage.input_tokens", usage.prompt_tokens)
                span.set_attribute("gen_ai.usage.output_tokens", usage.completion_tokens)
                record_llm_tokens("openai", self.model_name, usage.prompt_tokens, usage.completion_tokens)
        except Exception as exc:
            record_span_error(span, exc)
            raise
        finally:
            llm_latency.record(
                (perf_counter() - start) * 1000.0,
                {"gen_ai.system": "openai", "gen_ai.request.model": self.model_name},
            )
            span.end()

    async def embed_texts(self, texts: Sequence[str]) -> list[list[float]]:
        with llm_span("llm.embed_texts", "openai", self.model_name) as span:
            span.set_attribute("gen_ai.embed.input_count", len(texts))
            response = await self.client.embeddings.create(
                model=self.model_name,
                input=list(texts),
                dimensions=self.settings.embedding_dimension,
            )
            if response.usage:
                span.set_attribute("gen_ai.usage.input_tokens", response.usage.prompt_tokens)
                record_llm_tokens("openai", self.model_name, response.usage.prompt_tokens, None)
            return [item.embedding for item in response.data]
